### ISSUE TITLE
Non owner of a game is allowed to kick players.

### ISSUE THREAD

**Issue by Tejpbit** [Kerp1/Hastings#77]
The kick feature shouldn't be available to anyone but the creator of a game.

**Comment by Kalior** [comment]
You sure about this? And I assume you are referring to the owner of a game, as those will be different.

**Comment by Tejpbit** [comment]
Yep, i meant owner. Creator is owner at first I guess. But ownership is transferred if creator leaves, yes?

Observation were made on development branch just now. Connect two clients. Create a game with the first. Join that game with the second and kick the first. The firsts clients DOM is set to that of the lobby. 

However the list in the game stays the same. Either the DOM isn't updating Or the first client isn't kicked but the wrong DOM is displayed.

**Comment by Kalior** [comment]
Yes, I acknowledged this problem with the list of players not updated when working on #70 and fixed it right there and then, I believe. 

And yes, ownership is transferred to the player that has been in the game the longest.

**Comment by Tejpbit** [comment]
Did checkout #70 branch. That seems less buggy. If a player is kicked it's actually removed from the player list in the game.
But anyone can still kick the owner, which is the creator in this case. Did same procedure as in my last comment to replicate.

**Comment by Kalior** [comment]
Yes, everyone can kick anyone. It's an easy fix if we don't want it so. Will fix.
